// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RegisterRegisterPostData, RegisterRegisterPostResponse, LoginLoginPostData, LoginLoginPostResponse, ReadUsersMeUsersMeGetResponse } from './types.gen';

/**
 * Register
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const registerRegisterPost = (data: RegisterRegisterPostData): CancelablePromise<RegisterRegisterPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: 'http://localhost:8000/register',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Login
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const loginLoginPost = (data: LoginLoginPostData): CancelablePromise<LoginLoginPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: 'http://localhost:8000/login',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Users Me
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const readUsersMeUsersMeGet = (): CancelablePromise<ReadUsersMeUsersMeGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: 'http://localhost:8000/users/me'
}); };