// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type UserCreate = {
    username: string;
    password: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterRegisterPostData = {
    requestBody: UserCreate;
};

export type RegisterRegisterPostResponse = (unknown);

export type LoginLoginPostData = {
    requestBody: UserCreate;
};

export type LoginLoginPostResponse = (unknown);

export type ReadUsersMeUsersMeGetResponse = (unknown);

export type CreateNewChatChatPostResponse = (unknown);

export type SendMessageMessagePostData = {
    chatId: number;
    message: string;
};

export type SendMessageMessagePostResponse = (unknown);

export type GetChatsChatsGetResponse = (unknown);

export type GetMessagesMessagesChatIdGetData = {
    chatId: number;
};

export type GetMessagesMessagesChatIdGetResponse = (unknown);