// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type UserCreate = {
    username: string;
    password: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterRegisterPostData = {
    requestBody: UserCreate;
};

export type RegisterRegisterPostResponse = (unknown);

export type LoginLoginPostData = {
    requestBody: UserCreate;
};

export type LoginLoginPostResponse = (unknown);

export type ReadUsersMeUsersMeGetResponse = (unknown);

export type CreateNewChatChatPostResponse = (unknown);

export type GetChatsChatsGetResponse = (unknown);
export type GetChatsAnonymousChatResponse = (unknown)
export type GetChatsChatByUserResponse = (unknown)

export type GetChatChatsChatIdGetData = {
    chatId: string;
};

export type GetChatChatsChatIdGetResponse = (unknown);

export type GetChatMessagesChatsChatIdMessagesGetData = {
    chatId: string;
};

export type GetChatsChatByUserGetData = {
    userId: string;
};
export type GetChatMessagesChatsChatIdMessagesGetResponse = (unknown);

export type CreateAnonymousChatAnonymousChatsPostResponse = (unknown);

export type ValidateTokenValidateTokenGetResponse = (unknown);